name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  tag-tickets:
    runs-on: ubuntu-latest
    needs: [initialize]
    if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' || github.event_name == 'pull_request' }}
    steps:
      - name: Tag tickets
        run: echo "Tagging tickets for branch ${{ github.ref_name }}"
